// src/api/mockData.js

// Helper function to create dates relative to today (August 7, 2025)
const getRelativeDate = (daysAgo, hoursAgo = 0, minutesAgo = 0) => {
  const date = new Date("2025-08-07T12:00:00.000Z"); // Set a consistent "now"
  date.setDate(date.getDate() - daysAgo);
  date.setHours(date.getHours() - hoursAgo);
  date.setMinutes(date.getMinutes() - minutesAgo);
  return date;
};

export const leads = [
  {
    name: "919911114481",
    title: "9911**4481MAS",
    patient_full_name: "Awtar Sodhi",
    mobile: "919911114481",
    whatsapp_no: "+919911114481",
    gender: "Male",
    age: "83",
    language: "Hindi",
    camp: "Gurugram-23-08-2025",
    team: "Dr. Pankaj Mehto",
    knee_lead_status: "Xray Requested",
    journey_stage: "Assessment",
    current_bottleneck: "X-ray pending from patient",
    city: "Delhi",
    priority: "Medium",
    record_type: "Facebook Ad",
    case_type: "Hip",
    xray_assessment: "Pending",
    last_followup: "5 days ago",
    contact_person: "Son - Rohit Sodhi",
    medical_history: "Diabetes, Hypertension",
    pain_since_years: "2.5",
    pain_since: "Years",
    pain_increase_while: "Waking",
    pain_location: "Medial Joint Line",
    pain_complain: "C/O-Pain in both hip joints for the past 2.5 years",
    xray_request_status: "Requested",
    xray_request_date_time: getRelativeDate(5, 1).toISOString(),
    mode_of_request: "Phone Call",
    created_time: getRelativeDate(6),
    hasXray: true,
    hasMessages: true,
    type: "hip",
    major_events: {
      vc_done: true,
      xray_received: false,
      opd_done: false,
      mediclaim: true,
    },
    status_change_log: [
      {
        old_status: "Open",
        new_status: "Xray Requested",
        from_date: getRelativeDate(5, 1, 15).toISOString(),
        user: "medicalcoordinator@sahajclinic.com",
        team: "Dr. Pankaj Mehto",
      },
    ],
  },
  {
    name: "9876543210",
    title: "9876**3210",
    patient_full_name: "Rajesh Kumar",
    mobile: "9876543210",
    whatsapp_no: "+919876543210",
    gender: "Male",
    age: "45",
    language: "Hindi",
    camp: "Delhi-15-08-2025",
    team: "Krishna Choudhary",
    knee_lead_status: "Call Back",
    journey_stage: "New Lead",
    current_bottleneck: "Patient not reachable - 3 attempts made",
    city: "Delhi",
    priority: "High",
    record_type: "Google Ad",
    case_type: "Knee",
    xray_assessment: "Not Done",
    last_followup: "Today",
    contact_person: "Self",
    medical_history: "No known allergies",
    pain_since_years: "1",
    pain_since: "Years",
    pain_increase_while: "Climbing Stairs",
    pain_location: "Lateral Joint Line",
    pain_complain: "Knee pain while walking and climbing stairs",
    created_time: getRelativeDate(0, 2, 30), // Created 2.5 hours ago
    hasXray: false,
    hasMessages: false,
    type: "knee",
    major_events: {
      vc_done: false,
      xray_received: false,
      opd_done: false,
      mediclaim: false,
    },
    status_change_log: [],
  },
  {
    name: "8765432109",
    title: "8765**2109",
    patient_full_name: "Priya Sharma",
    mobile: "8765432109",
    whatsapp_no: "+918765432109",
    gender: "Female",
    age: "38",
    language: "English",
    camp: "Mumbai-20-08-2025",
    team: "Dr. Pankaj Mehto",
    knee_lead_status: "OPD Booked",
    journey_stage: "Treatment",
    current_bottleneck: "No specific bottleneck identified",
    city: "Mumbai",
    priority: "Medium",
    record_type: "Referral",
    case_type: "Other",
    xray_assessment: "Grade 2 OA",
    last_followup: "2 days ago",
    contact_person: "Husband - Amit Sharma",
    medical_history: "Previous knee surgery 2019",
    pain_since_years: "3",
    pain_since: "Years",
    pain_increase_while: "Morning",
    pain_location: "Bilateral",
    pain_complain: "Bilateral knee pain, morning stiffness",
    created_time: getRelativeDate(0, 0, 45), // Created 45 minutes ago
    hasXray: true,
    hasMessages: true,
    type: "knee",
    major_events: {
      vc_done: true,
      xray_received: true,
      opd_done: true,
      mediclaim: false,
    },
    status_change_log: [
      {
        old_status: "Interested",
        new_status: "OPD Booked",
        from_date: getRelativeDate(2).toISOString(),
        user: "telecaller@sahajclinic.com",
        team: "Dr. Pankaj Mehto",
      },
    ],
  },
  {
    name: "7654321098",
    title: "7654**1098",
    patient_full_name: "Sunita Devi",
    mobile: "7654321098",
    whatsapp_no: "+917654321098",
    gender: "Female",
    age: "62",
    language: "Hindi",
    camp: "Indore-10-09-2025",
    team: "Krishna Choudhary",
    knee_lead_status: "Open",
    journey_stage: "New Lead",
    current_bottleneck: null,
    city: "Indore",
    priority: "Low",
    record_type: "Walk-in",
    case_type: "Knee",
    xray_assessment: "Required",
    last_followup: "10 days ago",
    contact_person: "Self",
    medical_history: "None",
    pain_since_years: "5",
    pain_since: "Years",
    pain_increase_while: "Standing for long",
    pain_location: "Anterior",
    pain_complain: "Constant dull ache in the right knee.",
    created_time: getRelativeDate(10),
    hasXray: false,
    hasMessages: true,
    type: "knee",
    major_events: {
      vc_done: false,
      xray_received: false,
      opd_done: false,
      mediclaim: true,
    },
    status_change_log: [],
  },
];
